// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bwaCrixalis.Server.Data;

#nullable disable

namespace bwaAvernus.Server.Migrations.CrixalisDbContext_LogMigrations
{
    [DbContext(typeof(CrixalisDbContext_Log))]
    [Migration("20231014032334_dbAvernus_Log")]
    partial class dbAvernus_Log
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pantheon.Shared.BaseEntityModels.pthT9Log", b =>
                {
                    b.Property<Guid>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aktivitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPv4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IPv6")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdApplication")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("IdForm")
                        .HasColumnType("bigint");

                    b.Property<string>("IdPrimaryKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JenisAktivitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("KodeInstruksi")
                        .HasColumnType("bigint");

                    b.Property<string>("Kolom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PKDetil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TabelDetil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IdLog");

                    b.ToTable("T9Log");
                });
#pragma warning restore 612, 618
        }
    }
}
